apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gv9dksh06-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gv9dksh06-go 
  name: gv9dksh06-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gv9dksh06-go 
